### ISSUE TITLE
Crash on lost connection

### ISSUE THREAD

**Issue by sly74fr** [dwighthubbard/python-dlipower#30]
No handlers could be found for logger "dlipower.dlipower"
Traceback (most recent call last):
  File "test_wrapper.py", line 23, in <module>
    pdu.off(i)
  File "/home/xtramgr/Dev/VirtualEnvs/AIT/local/lib/python2.7/site-packages/dlipower/dlipower.py", line 419, in off
    self.geturl(url='outlet?%d=OFF' % self.determine_outlet(outlet))
  File "/home/xtramgr/Dev/VirtualEnvs/AIT/local/lib/python2.7/site-packages/dlipower/dlipower.py", line 381, in determine_outlet
    outlets = self.statuslist()
  File "/home/xtramgr/Dev/VirtualEnvs/AIT/local/lib/python2.7/site-packages/dlipower/dlipower.py", line 447, in statuslist
    url = self.geturl('index.htm')
  File "/home/xtramgr/Dev/VirtualEnvs/AIT/local/lib/python2.7/site-packages/dlipower/dlipower.py", line 373, in geturl
    logger.debug('Response code: %s', request.status_code)
AttributeError: 'NoneType' object has no attribute 'status_code'

**Comment by sly74fr** [comment]
Hello,

Any news on this issue ?

Best regards,
Sly

**Comment by sly74fr** [comment]
Hello,
Still no news ?
Best regards,
Sly

**Comment by sly74fr** [comment]
Hello,
Any problem with my patch ?
Best regards,
Sly

**Comment by sly74fr** [comment]
Hello,
Any news on this issue ?
